site_name: Curso CEFIRE Markdown - Pablo Rabasco
docs_dir: "md"
site_dir: "docs"

nav:
    - Inicio: index.md
    - Tema 1:
      - Apartado 1: tema1/apartado1.md
      - Apartado 2: tema1/apartado2.md
    - About: about.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

theme:
  name: 'material'
  logo: 'img/logoMarkdown.png'
  favicon: 'img/logoMarkdown.png'
  palette:
    primary: 'white'


